### ISSUE TITLE
Insert tags don't work in the templates

### ISSUE THREAD

**Issue by jankout** [terminal42/contao-node#18] opened 2020-04-16 19:59 UTC
Unfortunately, both new insert tags don't work in the templates. I tried it in _news_full.html5_ and it didn't work. Can you check it, please? Thank you

**Comment by qzminski** [comment] 2020-04-21 11:16
I am unable to reproduce the issue. Can you tell me what insert tags did you use exactly and are you sure they reference the existing nodes of the "content" (and not "folder") type?

**Comment by jankout** [comment] 2020-04-22 07:22
Yes, the nodes, I want to insert, are in a folder. But I'm trying to put the nodes directly, not the folder. If I put it into the _news_full.html5_ nothing will appear. I used e.g. `{{insert_node::14}}` and put it into 
```
<div class="invisible">
{{insert_node::14}}
</div>
```

 Nothing will appear within the div tag.

**Comment by qzminski** [comment] 2020-04-22 07:38
Honestly I am not sure what can be wrong. Have you got this case on a remote server? Would you be able to give me temporary access details (Contao backend + SFTP) to debug it?

**Comment by Toflar** [comment] 2020-06-12 07:07
That's really not something that can be related to that bundle. Insert tags are replaced globally and by the way: they work just fine for me. Closing.

**Closed by Toflar** 2020-06-12 07:07 UTC
Labels: bug, question
